name: Lint GitHub Actions

on:
  pull_request:
    branches:
      - main

    paths:
      - '.github/workflows/*.yml'

jobs:
  shellcheck:
    name: Run actionlint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run actionlint
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "::add-matcher::.github/matchers/actionlint.json"

          gh extension install cschleiden/gh-actionlint
          gh actionlint -color
        shell: bash
